# Generated by Django 4.2.11 on 2024-04-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_bookingdate_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
